### ISSUE TITLE
Sync fails.  Is this a bug or am I doing something wrong?

### ISSUE THREAD

**Issue by firecube** [resin-os/resin-device-toolbox#45]
Hi,

If I push a container that hasn't changed and rdt offers to sync the working directory I get the following error.  If I stop the container manually and push everything works as expected.  

Am I doing something wrong?

Thanks, Simon

* Syncing..
| Syncing to /usr/src/app on 'mosquitto'...nsenter: failed to execute 626: No such file or directory
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.0]
Synced /usr/src/app on 'mosquitto'.
Application container started after failed 'sync'.
rdt push failed. Error: Child process exited with code 12 Error: Child process exited with code 12
    at /usr/lib/node_modules/resin-device-toolbox/node_modules/resin-sync/build/shell.js:93:11
    at tryCatcher (/usr/lib/node_modules/resin-device-toolbox/node_modules/rindle/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/resin-device-toolbox/node_modules/rindle/node_modules/bluebird/js/main/promise.js:508:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/resin-device-toolbox/node_modules/rindle/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/lib/node_modules/resin-device-toolbox/node_modules/rindle/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/lib/node_modules/resin-device-toolbox/node_modules/rindle/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/resin-device-toolbox/node_modules/rindle/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/resin-device-toolbox/node_modules/rindle/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by lekkas** [comment]
Hey @firecube , 

Can you please give us the following information?

* Your node version (`node -v`)
* Your `resin-device-toolbox` version (`rdt version`)
* Your device type
* And finally, was the resinOS image downloaded from resinos.io? If so, can you please paste its development release version? 

Thank you,
Kostas

**Comment by firecube** [comment]
Hi,

Node is version 6.9.1, rdt is 0.0.6.

My device is a Raspbery Pi 1.

Yes, resinOS image downloaded from your website but I'm not sure how I get
the development release version?

Thanks, Simon

**Comment by lekkas** [comment]
Thank you @firecube. There's a known bug in `resinOS 2.0.0-beta.1 ` where the `ssh` daemon of the device is not working. Just to verify that this is indeed the case, can you please try `rdt ssh` to your device? If my theory is correct, it should fail.

The reason why this is connected to the sync issue is that the `sync` rdt feature uses `ssh` to `rsync` the changes to your container - so with `ssh` not working, `rdt` will fail (and in a rather noisy manner apparently)

**Comment by firecube** [comment]
Sorry, I can't retest this as I had other issues... https://github.com/resin-os/resinos/issues/132

I will get this set up on a new image and try again.

Thanks, Simon
