### ISSUE TITLE
Cannot find module 'ip' error when using it with node v4

### ISSUE THREAD

**Issue by imrehg** [resin-os/resin-device-toolbox#54]
Running rdt node.js v4, get the following error:

```
$ rdt 
module.js:327
    throw err;
    ^

Error: Cannot find module 'ip'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/greg/.nvm/versions/node/v4.4.7/lib/node_modules/resin-device-toolbox/node_modules/resin-sync/node_modules/resin-discoverable-services/build/discoverable.js:30:8)
    at Object.<anonymous> (/home/greg/.nvm/versions/node/v4.4.7/lib/node_modules/resin-device-toolbox/node_modules/resin-sync/node_modules/resin-discoverable-services/build/discoverable.js:416:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/greg/.nvm/versions/node/v4.4.7/lib/node_modules/resin-device-toolbox/node_modules/resin-sync/build/discover.js:24:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/greg/.nvm/versions/node/v4.4.7/lib/node_modules/resin-device-toolbox/node_modules/resin-sync/build/index.js:25:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/greg/.nvm/versions/node/v4.4.7/lib/node_modules/resin-device-toolbox/build/actions/sync.js:17:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/greg/.nvm/versions/node/v4.4.7/lib/node_modules/resin-device-toolbox/build/actions/index.js:20:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

It installed fine, without any errors.

Tested with v4.4.7 (from user report), and v4.7.0 (latest v4 version). Node >= 4 is recommended in the Readme.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_xsw)

**Comment by Page-** [comment]
This is actually an issue in resin-discoverable-services, I've PRed a fix in https://github.com/resin-io-modules/resin-discoverable-services/pull/27
